sudo: required

language: generic

services:
- docker

install:
- docker pull jlimperg/agda-stdlib:2.5.4.2_0.17

script:
- docker run -v $TRAVIS_BUILD_DIR:/build jlimperg/agda-stdlib:2.5.4.2_0.17 /bin/sh -c 'cd /build/tools/everything && stack --allow-different-user setup && cd /build && make STACKOPTS=--allow-different-user'
